version: "3"
services:
  api:
    build: api-container/
    volumes:
      - ./api-container/app:/src/
    ports:
      - 9090:9090
  gui:
    image: nginx:1.17.9
    volumes:
      - ./gui-container/frontend/dist:/usr/share/nginx/html
      - ./gui-container/nginx:/etc/nginx/conf.d
  nginx:
    image: nginx:1.17.9
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx-container:/etc/nginx/conf.d
    restart: always
